urls.py
# -*- coding:utf-8 -*-
#

from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

import settings

urlpatterns = patterns('',

    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes':True }),
    
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    
    # Hacky ajax shit ... 
    (r'^news/single/(\d+)', 'news.views.single'),
    (r'^imggal/get_images_for/(\d+)', 'imggal.views.get_images_for'),


    (r'^', include('cms.urls')),
)

cmsplugin_contact/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models.pluginmodel import CMSPlugin

class Contact(CMSPlugin):
	SPAM_PROTECTION_CHOICES = (
	    (0, 'Honeypot'),
	    (1, 'Akismet'),
	    (2, 'ReCAPTCHA'),
	)
    
	THEME_CHOICES = (
	    ('clean', 'Clean'),
	    ('red', 'Red'),
	    ('white', 'White'),
	    ('blackglass', 'Black Glass'),
        ('custom', 'Custom'),
	)
	
	site_email 	= models.EmailField(_('Email recipient'))
	email_label 	= models.CharField(_('Email sender label'), default=_('Your email address'), max_length=100)
	subject_label	= models.CharField(_('Subject label'), default=_('Subject'), max_length=200)
	content_label 	= models.CharField(_('Message content label'), default=_('Message'), max_length=100)
	thanks 		= models.CharField(verbose_name=_("Thanks message"), help_text=_('Message displayed on successful submit'), default=_('Thank you for your message.'), max_length=200)
	submit		= models.CharField(_('Submit button value'), default=_('Submit'), max_length=30)
	
	spam_protection_method = models.SmallIntegerField(verbose_name=_('Spam protection method'), choices=SPAM_PROTECTION_CHOICES, default=0)
    
	akismet_api_key = models.CharField(max_length=255, blank=True)
	
	recaptcha_public_key = models.CharField(max_length=255, blank=True)
	recaptcha_private_key = models.CharField(max_length=255, blank=True)
	recaptcha_theme = models.CharField(max_length=20, choices=THEME_CHOICES, default='clean', verbose_name=_('ReCAPTCHA theme'))
	
	def __unicode__(self):
		return self.site_email

cmsplugin_contact/forms.py
from django import forms
#import settings
from stopspam.forms import HoneyPotForm, RecaptchaForm, AkismetForm
  
class HoneyPotContactForm(HoneyPotForm):
    email 	= forms.EmailField()
    subject	= forms.CharField(required=False)
    content	= forms.CharField(widget=forms.Textarea())


class AkismetContactForm(AkismetForm):
    akismet_fields = {
        'comment_author_email': 'email',
        'comment_content': 'content'
    }
    email     = forms.EmailField()
    subject    = forms.CharField(required=False)
    content    = forms.CharField(widget=forms.Textarea())
    
    akismet_api_key = None
    

class RecaptchaContactForm(RecaptchaForm):
    email     = forms.EmailField()
    subject    = forms.CharField(required=False)
    content    = forms.CharField(widget=forms.Textarea())

    recaptcha_public_key = None
    recaptcha_private_key = None
    recaptcha_theme = None

cmsplugin_contact/templates/cmsplugin_contact/admin/plugin_change_form.html
{% extends "admin/cms/page/plugin_change_form.html" %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript">
//<![CDATA[
(function($) {
	function updateVisibility(class_prefix) {
		$('div.spam_protection_method').parent().children('.form-row').each(function(index, row) {
			var visible = false;
			$.each($(row).attr('class').split(/\s+/), function(index, class) {
				if (class == 'spam_protection_method' || class.indexOf(class_prefix) >= 0) {
					visible = true;
				}
			});
			if (visible) {
				$(row).css('display', 'block');
			} else {
				$(row).css('display', 'none');
			}
		});
	}
	
	$(document).ready(function(){
		
		$('#id_spam_protection_method').change(function() {
			var curOption = $('#id_spam_protection_method :selected');
			updateVisibility(curOption.html().toLowerCase());
		});
	});
})(jQuery);
//]]>
</script>

{% endblock extrahead %}

{% block extrastyle %}{{ block.super }}
<style type="text/css">
	div.form-row label {
		width: 14em;
	}
	form .aligned p.help {
		padding-left: 48px;
		margin-left: 13em;
	}
	
	{% if spam_protection_method != 1 %}
	div.form-row.akismet_api_key {
		display: none;
	}
	{% endif %}

	{% if spam_protection_method != 2 %}
	div.form-row.recaptcha_public_key {
		display: none;
	}
	div.form-row.recaptcha_private_key {
		display: none;
	}
	div.form-row.recaptcha_theme {
		display: none;
	}
	{% endif %}
</style>
{% endblock extrastyle %}